# Generated by Django 3.2.5 on 2021-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.PositiveIntegerField()),
                ('pointFaible', models.TextField()),
                ('pointFort', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
