# Generated by Django 3.2.5 on 2021-08-19 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimatePrice', models.PositiveIntegerField()),
                ('signatureDate', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('phase', models.CharField(max_length=150)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produit')),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prospect')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
