# Generated by Django 3.2.5 on 2021-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_opportunities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('startDate', models.CharField(max_length=150)),
                ('starttime', models.CharField(max_length=150)),
                ('endDate', models.CharField(max_length=150)),
                ('endtime', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
            ],
        ),
    ]
