# Generated by Django 3.2.5 on 2021-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='action',
            field=models.ManyToManyField(to='api.Action'),
        ),
    ]
