# Generated by Django 3.2.5 on 2021-08-27 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_opportunities_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunities',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='Opportunity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.opportunities'),
        ),
    ]
