# Generated by Django 3.2.5 on 2021-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210827_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='endtime',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
