# Generated by Django 3.2.5 on 2021-08-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_prospect_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
