# Generated by Django 3.2.5 on 2021-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='creationDate',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
