# Generated by Django 3.2.5 on 2021-09-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_opportunities_estimateprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='duration',
        ),
        migrations.AddField(
            model_name='action',
            name='Contact',
            field=models.ManyToManyField(null=True, to='api.Contact'),
        ),
    ]
