# Generated by Django 3.2.5 on 2021-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_action_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='Contact',
            field=models.ManyToManyField(blank=True, to='api.Contact'),
        ),
    ]
