# Generated by Django 3.2.5 on 2021-09-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210901_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='delete',
            field=models.BooleanField(null=True),
        ),
    ]
