# Generated by Django 3.2.5 on 2021-09-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_opportunities_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='function',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
