# Generated by Django 3.2.5 on 2021-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='delete',
            field=models.BooleanField(null=True),
        ),
    ]
