# Generated by Django 3.2.5 on 2021-10-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210915_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
