# Generated by Django 3.2.5 on 2021-10-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_pays_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='pays',
        ),
        migrations.AddField(
            model_name='pays',
            name='Ville',
            field=models.ManyToManyField(blank=True, to='api.Ville'),
        ),
    ]
