# Generated by Django 3.2.5 on 2021-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20211005_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='delete',
            field=models.BooleanField(null=True),
        ),
    ]
