# Generated by Django 3.2.5 on 2021-10-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_ville_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
