# Generated by Django 3.2.5 on 2021-10-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_ville_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pays',
            name='Ville',
        ),
        migrations.AddField(
            model_name='pays',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prospect'),
        ),
    ]
