# Generated by Django 3.2.5 on 2021-10-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20211005_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='delete',
            field=models.BooleanField(null=True),
        ),
    ]
