# Generated by Django 3.2.5 on 2021-10-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_ville_pays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ville',
            old_name='pays',
            new_name='Pays',
        ),
    ]
