# Generated by Django 3.2.5 on 2021-10-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_pays_ville_pays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pays',
            old_name='pays',
            new_name='name',
        ),
    ]
