# Generated by Django 3.2.5 on 2021-10-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_pays_pays_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='Pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pays'),
        ),
    ]
