# Generated by Django 3.2.5 on 2021-10-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_ville_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.PositiveIntegerField()),
                ('pointFaible', models.TextField()),
                ('pointFort', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('delete', models.BooleanField(null=True)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produit')),
            ],
        ),
    ]
