# Generated by Django 3.2.5 on 2021-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
