# Generated by Django 3.2.5 on 2021-10-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20211006_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='code',
        ),
    ]
