# Generated by Django 3.2.5 on 2021-10-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_competition_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='Ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ville'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pays'),
        ),
    ]
