# Generated by Django 3.2.5 on 2021-10-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20211010_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='type',
        ),
    ]
