# Generated by Django 3.2.5 on 2021-10-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_produit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.typeproduit'),
        ),
    ]
