# Generated by Django 3.2.5 on 2021-10-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_produit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='Contact',
            field=models.ManyToManyField(blank=True, to='api.Contact'),
        ),
    ]
