# Generated by Django 3.2.5 on 2021-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_opportunities_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='principale',
            field=models.BooleanField(null=True),
        ),
    ]
