# Generated by Django 3.2.5 on 2021-10-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_contact_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='Rib',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='activity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='banque',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='codePostal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='langue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
