# Generated by Django 3.2.5 on 2021-10-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20211012_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
