# Generated by Django 3.2.5 on 2021-10-13 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_prospect_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ville'),
        ),
        migrations.AddField(
            model_name='contact',
            name='adresse',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pays'),
        ),
    ]
