# Generated by Django 3.2.5 on 2021-11-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20211111_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='emai@gmail.com', max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='8888888', max_length=100),
        ),
    ]
