# Generated by Django 3.2.5 on 2021-11-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_produit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ville'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='activity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='delete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='langue',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pays'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='type',
            field=models.CharField(max_length=150),
        ),
    ]
