# Generated by Django 3.2.5 on 2021-11-11 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0071_alter_prospect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='Contact',
            field=models.ManyToManyField(to='api.Contact'),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='creationDate',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit'),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prospect'),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.newuser'),
        ),
    ]
