# Generated by Django 3.2.5 on 2021-11-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20211111_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='estimatePrice',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
