# Generated by Django 3.2.5 on 2021-11-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20211111_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
