# Generated by Django 3.2.5 on 2021-11-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20211119_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='delete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='delete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='delete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ville',
            name='delete',
            field=models.BooleanField(),
        ),
    ]
