# Generated by Django 3.2.5 on 2021-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20211119_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
