# Generated by Django 3.2.5 on 2022-02-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_remove_ville_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
