# Generated by Django 3.2.5 on 2022-02-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_produit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langues',
            name='langue',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
