# Generated by Django 3.2.5 on 2022-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_langues_langue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='ville',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
