# Generated by Django 3.2.5 on 2022-02-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_ville_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('delete', models.BooleanField()),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ville')),
            ],
        ),
    ]
