# Generated by Django 3.2.5 on 2021-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20210806_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
