# Generated by Django 3.2.5 on 2021-10-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20211015_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='birthday',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
