# Generated by Django 3.2.5 on 2021-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20211015_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='Color',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
