# Generated by Django 3.2.5 on 2021-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_newuser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
