# Generated by Django 3.2.5 on 2022-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_newuser_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='delete',
            field=models.BooleanField(),
        ),
    ]
