# Generated by Django 3.2.5 on 2022-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_alter_newuser_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='Color',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Ville',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='pays',
            field=models.CharField(max_length=150),
        ),
    ]
