from api import views
from django.conf import urls
from django.urls import path


urlpatterns = [
    path('products', views.ProduitListe.as_view() ),
    path('prospects', views.ProspectListe.as_view() ),
    path('Contact', views.ContactListe.as_view() ),
    path('Allopportunities/', views.OpportunitiesListe.as_view() ),
    path('WinnningOpportunities/', views.OpportunitiesListeWinning.as_view() ),
    path('AllopportunitiesNopa/', views.OpportunitiesListeNopa.as_view() ),
     path('opportunitiesQualification/', views.OpportunitiesListeQualification.as_view() ),
    path('opportunitiesEtude/', views.OpportunitiesListeEtude.as_view() ),
    path('opportunitiesProposition/', views.OpportunitiesListeProposition.as_view() ),
    path('opportunitiesNegociation/', views.OpportunitiesListeNegociation.as_view() ),
    path('opportunitiesGagnee/', views.OpportunitiesListeGagnee.as_view() ),
    path('opportunitiesPerdue/', views.OpportunitiesListePerdue.as_view() ), 
    path('Updateopportunities/<int:pk>', views.OpportunitiesRetrieveUpdateDestroyAPIView.as_view() ),
    path('UpdateAction/<int:pk>', views.ActionRetrieveUpdateDestroyAPIView.as_view() ),
    path('UpdateProduit/<int:pk>', views.ProduitRetrieveUpdateDestroyAPIView.as_view() ),
    path('opportunityDetaills/<int:pk>', views.OpportunityDetaills.as_view() ),
    path('emailListe/<int:pk>', views.emailListe.as_view() ),
    path('callListe/<int:pk>', views.callListe.as_view() ),
    path('meetingListe/<int:pk>', views.meetingListe.as_view() ),
    path('ActionListe/', views.ActionListe.as_view() ),
    path('sumQualification/', views.SumQualification1.as_view() ),
    path('sumEtude/', views.SumEtude.as_view() ),
    path('Sumproposition/', views.Sumproposition.as_view() ),
    path('SumNegociation/', views.SumNegociation.as_view() ),
    path('SumGagnee/', views.SumGagnee.as_view() ),
    path('SumPerdu/', views.SumPerdu.as_view() ),
    path('UserLogged/', views.UserLogged.as_view() ),
    path('ActionDetaills/<int:pk>', views.ActionDetaills.as_view() ),
    path('ProduitDetaills/<int:pk>', views.ProduitDetaills.as_view() ),
    path('ProspectDetaills/<int:pk>', views.ProcpectDetaills.as_view() ),
    path('UpdateProspect/<int:pk>', views.ProspectRetrieveUpdateDestroyAPIView.as_view() ),
    path('ContactDetaills/<int:pk>', views.ContactDetaills.as_view() ),
    path('UpdateContact/<int:pk>', views.ContactRetrieveUpdateDestroyAPIView.as_view() ),
    path('UserLogged',  views.UserLogged.as_view()),
]